spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: update
  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE